SELECT TOP (1000) [OrderId]
      ,[OrderDate]
      ,[ProductCode]
      ,[ProductName]
      ,[CustomerId]
      ,[CustomerName]
      ,[City]
      ,[StateCode]
      ,[ItemTotalCost]
  FROM [CourseSalesDb].[dbo].[vw_OrderDetail]
