SELECT TOP (1000) [OrderId]
      ,[OrderDate]
      ,[OrderStatus]
      ,[CustomerId]
      ,[CustomerName]
      ,[City]
      ,[StateCode]
      ,[OrderTotal]
  FROM [CourseSalesDb].[dbo].[vw_OrderSummary]
